service: triaging
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: prototypefund
  environment:
    APP_ID: ""
    PRIVATE_KEY: ""
    WEBHOOK_SECRET: ""
    NODE_ENV: production
    LOG_LEVEL: debug

functions:
  webhooks:
    handler: handler.webhooks
    events:
      - httpApi:
          path: /api/github/webhooks
          method: post
